### ISSUE TITLE
Not using default port, not listening to nornir inventory file. 

### ISSUE THREAD

**Issue by andreas1o** [DataKnox/nornir_pyez#11]
Hi using this
I dosen't seem like it picks up the port from the inventory file served by nornir 

Sample inventory file

host_1:
   hostname: host_1
   port: 22 

Error message in nornir.log

ncclient.transport.errors.SSHError: Could not open socket to host_1:830

**Comment by DataKnox** [comment]
Updated connector to allow port param. Default port, if not specified, is 830 (NETCONF)
