### ISSUE TITLE
Can we store the unique configuration under hosts.yaml or group.yaml and retrive it as payload 

### ISSUE THREAD

**Issue by KedharnathGoud** [DataKnox/nornir_pyez#16]
I'm trying to Implement bulk missing config changes .These configs are unique to the device therefore I want to store those missing configs in my hosts.yaml under Config or Data and retrieve while in the payload is that possible with jinja templating if you so can you help me with the docs  or should I relay on Netmiko ,Naplam plugins for Nornir ?

**Comment by DataKnox** [comment]
This is a functionality of Nornir core. You may want to explore this repo for samples: https://github.com/DataKnox/NornirJunos/tree/main
