### ISSUE TITLE
pyez_cmd task plugin not returning any output for show commands

### ISSUE THREAD

**Issue by suhaibasaeed** [DataKnox/nornir_pyez#38]
I'm trying to execute some normal show commands on devices (MX240 and MX204 on 20.2R3-S3.6 code ) e.g. bgp summary and show chassis routing-engine but instead of receiving normal output it returns the below:

`Command launched, output: (False, 'show chassis routing-engine\r\r\nshow: Command not found.\r\n% ')`

My code looks like this:

```
def get_chassis_routing_engine_cpu_data(task):

    result_text = task.run(task=pyez_cmd, command='show chassis routing-engine')
    task.host["re_cpu_text"] = result_text[0].result
```

I'm using this task plugin instead of pyez_rpc as I would like the data in text format.

Thanks in advance

**Comment by penfold1972** [comment]
I think you may be giving it the incorrect command. Junos can give you the RPC command when you add “| display xml rpc” to the end of what you want to run. For example:
`show chassis routing-engine | display xml rpc`

gives the output:
```
<rpc-reply xmlns:junos=http://xml.juniper.net/junos/21.2R0/junos>
    <rpc>
        <get-route-engine-information>
        </get-route-engine-information>
    </rpc>
    <cli>
        <banner>{master:0}</banner>
    </cli>
</rpc-reply>
```

The RPC command you want to execute is given within the <rpc> tags… so the command you probably want in your code is:
```
def get_chassis_routing_engine_cpu_data(task):

    result_text = task.run(task=pyez_cmd, command='get-route-engine-information')
    task.host["re_cpu_text"] = result_text[0].result
```

I haven't tested this, but since nornir_pyez is still using pyez to connect to JunOS via netconf, I understand that you will still need to use the RPC commands rather than the normal CLI commands.

**Comment by suhaibasaeed** [comment]
Thanks for the prompt response.

I tried what you suggested and it just returned the exact same thing.

```
Command launched, output: (False, 'get-route-engine-information\r\r\nget-route-engine-information: Command not found.\r\n% ')
```

As I mentioned I'm trying to get the command out back in plain text format as opposed to the usual XML an RPC will return (or JSON in the case of this nornir-pyez plugin)

**Comment by penfold1972** [comment]
I never used this command before, so I went to [Juniper Documentation ](https://www.juniper.net/documentation/us/en/software/junos-pyez/junos-pyez-developer/topics/task/junos-pyez-program-shell-accessing.html) and saw it behaves differently than I thought.

```
def get_chassis_routing_engine_cpu_data(task):

    result_text = task.run(task=pyez_cmd, command='cli -c "show chassis routing-engine"')
    task.host["re_cpu_text"] = result_text[0].result

```
I haven't tested this either, but it seems like nornir_pyez is passing what you put in to the Juniper and that is where the error is coming from.

**Comment by suhaibasaeed** [comment]
This now works, thank you very much!

It does take quite long and returns the output in a strange format as shown below but I'll just look into trying this via an RPC instead. I'm happy to close this issue. 

```
Command launched, output: (False, 'cli -c "show chassis routing-engine"\r\r\n\r\r\n\r\r\nRouting Engine status:\r\n    Temperature                 45 degrees C / 113 degrees F\r\n    CPU temperature             46 degrees C / 114 degrees F\r\n    DRAM                      16334 MB (16384 MB installed)\r\n    Memory utilization           5 percent\r\n    5 sec CPU utilization:\r\n      User                       0 percent\r\n      Background                 0 percent\r\n      Kernel                     0 percent\r\n      Interrupt                  0 percent\r\n      Idle                     100 percent\r\n    1 min CPU utilization:\r\n      User                       0 percent\r\n      Background                 0 percent\r\n      Kernel                     0 percent\r\n      Interrupt                  0 percent\r\n      Idle                      99 percent\r\n    5 min CPU utilization:\r\n      User                       0 percent\r\n      Background                 0 percent\r\n      Kernel                     0 percent\r\n      Interrupt                  0 percent\r\n---(more)------(more)------(more)------(more)------(more)------(more)------(more)------(more)------(more)------(more)------(more)------(more)------(more)------(more)------(more)------(more)------(more)------(more)------(more)------(more)------(more)------(more)------(more)------(more)------(more)------(more)------(more)------(more)------(more)------(more)------(more)------(more)------(more)------(more)------(more)------(more)------(more)------(more)------(more)------(more)------(more)------(more)------(more)------(more)------(more)------(more)------(more)------(more)------(more)------(more)------(more)------
```

**Comment by penfold1972** [comment]
I'm curious if it's better when you use the command:
`'cli -c "show chassis routing-engine | no-more"'`
The idea is to eliminate pauses in the output by skipping the pagination feature.

**Comment by barriejc** [comment]
I have just issued [PR 41](https://github.com/DataKnox/nornir_pyez/pull/41) to modify the documentation on this since I ran into the same issue and didn't think to look here because this was closed.
